### ISSUE TITLE
[Bug]: precedence/ordering of @@access decorators is unclear

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/typespec-azure#1036]
### Describe the bug

I've got a question about `@@access`, when there are rules that overlap.

In our service we were attempting to make an operation public, only for the scope "go", but internal for everyone else. However, we couldn't do this:

```typespec
@@access(TestThing, Access.internal);
@@access(TestThing, Access.public, "go");
```

This generates this type graph:

```yaml
ModelTestThing
  properties:
    ModelPropertyname
      # extra stuff elided
      data:
         # NOTE that it just gave us all the same access.
         Symbol(@azure-tools/typespec-client-generator-core.access): { }
```

You can fix this by just ordering them differently:

```typespec
@@access(TestThing, Access.public, "go");
@@access(TestThing, Access.internal);
```

This generates this type graph:

```yaml
ModelTestThing
  properties:
    ModelPropertyname
      # extra stuff elided
      data:
         Symbol(@azure-tools/typespec-client-generator-core.access): { go: "public" }
```

I'm not entirely sure which behavior is the correct behavior, but I did find it surprising that the more specific directive was overridden by the least specific directive. The ordering of their declarations in the file doesn't seem like it should be a critical factor, especially given how these `@@access`'s could be in separate files altogether.

Including @l0lawrence and @lmazuel in case I've misstated the bug.

### Reproduction

[Playground Link](https://azure.github.io/typespec-azure/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdNUZdmVyc2lvbmluZ8wfYXp1cmUtdG9vbHMvyCstxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVVukAqMgbQcR5LkNvcmXSEi5UcmFpdHPPGeUAlUfoAJTHOwptb2RlbCBUZXN0VGjELXsKICAvKioKICAgKiBIZWxsbyB3b3JsZMURLwogIG5hbWU6IHN0cuUAjX0KCi8vIHJl5QFJbmcgdGhlIG9yZGVyIG9mxA1zZSBzdGF0ZW1lbnRzIHdpbGzET2sKQEBhY2Nlc3MoyXosIEHFEi5wdWJsaWMsICJnbyIpO9wqaW50ZXJuYWwpOwoKCg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40azure-tools%2Ftypespec-azure-rulesets%2Fdata-plane%22%5D%7D%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
