### ISSUE TITLE
Augment decorator (@@armProviderNamespace) value not getting picked up {service-name} in tspconfig.yaml

### ISSUE THREAD

**Issue by jglouie** [Azure/typespec-azure#122]
I am using this `@@armProviderNamespace(Microsoft.MyNamespace, "Private.MyNamespace")` syntax to override the ARM provider namespace, and the resulting generated swagger file is as intended - the operations use the `Private.MyNamespace` name as desired.

However, the `tspconfig.yaml` file references a value called `{service-name}` which uses the original value `Microsoft.MyNamespace`.
```
emit:
  - '@azure-tools/typespec-autorest'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: "{project-root}/../../.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/xxx.json"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
```

**Comment by timotheeguerin** [comment]
It is not possible today to get that value from autorest as arm library depends on autorest and not the other around. 

Changing this also would be a breaking change. The recommendation in this case would be to change `{service-name}` with  the value you want.


```yaml
emit:
  - '@azure-tools/typespec-autorest'
options:
  '@azure-tools/typespec-autorest':
    emitter-output-dir: "{project-root}/../../.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/Private.MyNamespace/{version-status}/{version}/xxx.json"
linter:
  extends:
    - "@azure-tools/typespec-azure-resource-manager/all"
```
