### ISSUE TITLE
[Bug]: TCGC, lroMetadata.finalResponse.resultPath is neither clientName nor serializedName

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/typespec-azure#2072]
### Describe the bug

TCGC 0.49.1

`lroMetadata.finalResponse.resultPath` is neither clientName nor serializedName

### Reproduction

https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvcmVzdCI7CskZYXp1cmUtdG9vbHMvyCUtxhVjb3Jl3ytjLWNsaWVudC1nZW5lcmF0b3LINgp1c2luZyBUeXBlU3BlYy5IdHRwO9AVUmVzdNEVVmVyc2lvbmluZ8gbQcR5LkNvcmXSEi5UcmFpdHPPGeUAlUfoAJTHOwpAc2VydmljZSh7CiAgdGl0bGU6ICJSZXNwb25zZSIsCn0pCkB2xn5lZChBcGnnAItzKQpuYW1lc3BhY2UgVHNwVGVzdOQAvMU4OwoKZW51bSDLLyDEYEB1c2VEZXBlbmRlbmN5KGdsb2JhbC7rALnILi52MV8wX1ByZXZpZXdfMikKICB2MjAyMl8wNl8wMV9wxhk6ICLEFS0wNi0wMS3HFeQAtAoKb3AgQ3VzdG9tTG9uZ1J1buQBO09w5AD7aW9uPAogIFRQYXJhbXMgZXh0ZW5kc%2BwBgGZsZWPEJy5Nb2RlbCzELegA2d8vZGVsCj4gaXMgRm91bmTFbHMu1HfEVUFjY2VwdGVkyVwm5QEkICBAcG9sbGluZ0xvY8U4xhVoZWFkZXIoIslPLcggIuQBHyAgb8gZyBg6IFJlc291cmNlyBI86QDJPjsKICB9Cj7kAgJyxyYoIsgKcyIpCm3kAM7JQuYBv3Zpc2liaWxpdHnELGFkxXppZDogc3Ry5QKcxCVrZXnZLOQCM80uZGVzY3JpcOQAnT%2FKGSAg5ANMyhB9CgovLyBubyDkAKJ1bHQiIHBy5ADvdHnnAKfpARVEZXRhaWznAm5kb2PrATAgSUTlAIT5AKEsICJjcmVhdGXpANd1dWlk5QCnc3RhdHVzOuwDZPUB41N0YXRl5ADAZXJyb3I%2F2TFFxB%2FFWkBscm9S5QDVxA3mBDpOYW1lKCJs6gK6xiHmAL5lbmNvZGVkxiRhcHBsaeYB3C9qc29u5ADEbHJvX%2BcBJ8Qxxgs%2F6gIN5QFPQPoEFS7mAIXlBBHmAbDpBBDGLyLkAr7nBDc68QP85gQz5QF7yBMiKQpAcm91dGUoIuQFbMgUaW50ZXJm5ARAyClPcCB75QEVyC5scm8t6wDMbHJvSW52YWxp5AM1dWx05ANr%2FgPnIOcDVCAgQGJvZHkgcmVxdWVzdOwBDsQdfeQA0yDxAkcKICA%2B5AEv&e=%40azure-tools%2Ftypespec-client-generator-core&options=%7B%7D

input
```
  @lroResult
  @clientName("longRunningResult")
  @encodedName("application/json", "lro_result")
  result?: Resource;
```

output
```
                - apiVersions:
                    - 2022-06-01-preview
                  type: *a4
                  name: longRunningResult
                  isGeneratedName: false
                  optional: true
                  isApiVersionParam: false
                  onClient: false
                  crossLanguageDefinitionId: TspTest.Response.OperationDetails.result
                  decorators: []
                  kind: property
                  discriminator: false
                  serializedName: lro_result
                  isMultipartFileInput: false
                  flatten: false

            result: *a4
            resultPath: result
```

The `resultPath` should be the client name of the property `longRunningResult`.

### Checklist

- [x] Follow our [Code of Conduct](https://github.com/azure/typespec-azure/blob/main/CODE_OF_CONDUCT.md)
- [x] Check that this issue is about the Azure libraries for typespec. For bug in the typespec language or core libraries file it in the [TypeSpec repo](https://github.com/Microsoft/TypeSpec/issues/new/choose)
- [x] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
